---
title: "Chi Squared"
output: html_document
date: "2023-04-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(gt)

# ****************
#If the standardized residual is greater than 2 or less than -2 in absolute value, then the cell is considered to be significantly contributing to the chi-squared statistic at a 5% level of significance.
#The standardized residual represents the number of standard deviations that the observed frequency deviates from the expected frequency
# ****************

rm(list = ls())

# sig_table <- function(rowData,colData,data) { #x and y should be the string names of the variables
#   
#   #LOOK TO MAKING A BANNER BY HAVING THE FUNCTION PARAMETERS BE function(rowData, data, ...) then using x <- list(...)
#   
#   xtabs <- xtabs(~data[[rowData]]+data[[colData]],data=data)
#   
#   chisq <- chisq.test(xtabs)
#   
#   std_res <- chisq$stdres
# 
#   # Convert to column percentages
#   xtabs <- prop.table(xtabs, margin = 2)
#   
#   mytable <- format(xtabs, justify = "right")
#   mytable[std_res > 2] <- paste(mytable[std_res > 2], intToUtf8(8593))
#   mytable[std_res < -2] <- paste(mytable[std_res < -2], intToUtf8(8595))
#   
#   mytable <- as.data.frame(mytable)
#   return(mytable)
# }

sig_table <- function(rowData,data, ...){

  tablelist <- list()
  
  cols <- list(...)
  
  # loop version 2
  for (i in 1:length(cols)) {

    xtabs <- xtabs(~data[[rowData]]+data[[cols[[i]]]],data=data)
    
    chisq <- chisq.test(xtabs)
  
    std_res <- chisq$stdres

    xtabs <- prop.table(xtabs, margin = 2)
    
    xtabs <- apply(xtabs, 2, round, digits = 2)
  
    mytable <- format(xtabs, justify = "right")
    mytable[std_res > 2] <- paste(mytable[std_res > 2], intToUtf8(8593))
    mytable[std_res < -2] <- paste(mytable[std_res < -2], intToUtf8(8595))
  
    mytable <- as.data.frame(mytable)
    
    tablelist[[i]] <- mytable
    names(tablelist)[i] <- cols[i]
    
  }
  
  table <- do.call(cbind, tablelist)
  
  oldcolnames <- colnames(table)
  newcolnames <- lapply(oldcolnames, function(x) sub("^[^.]*\\.", "", x))
  for (i in 1:length(newcolnames)) {
    names(newcolnames)[i] <- oldcolnames[i]
  }
  
  table$rowname <- row.names(table) 
  
  gt <- table %>%
    gt(rowname_col = "rowname")
  
  for (i in 1:length(cols)) {
    gt <- gt %>%
      tab_spanner(label = cols[i], columns = starts_with(cols[[i]]))
  }
  
  gt <- gt %>% cols_label(.list = newcolnames) %>% 
    cols_align(columns = everything(),
             align = "left")
  
  return(gt)
}  

```


```{r echo=TRUE}

sig_table("gear", mtcars, "cyl", "vs", "am", "carb")


newcolnames <- list("cyl.4" = "4",
                    "cyl.6" = "6",
                    "cyl.8" = "8",
                    "vs.0" = "0",
                    "vs.1" = "1"
                    )

```