---
title: "Significance Tables"
output:
  pdf_document:
     latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(gt)
library(gtExtras)
# ****************
#If the standardized residual is greater than 2 or less than -2 in absolute value, then the cell is considered to be significantly contributing to the chi-squared statistic at a 5% level of significance.
#The standardized residual represents the number of standard deviations that the observed frequency deviates from the expected frequency
# ****************

rm(list = ls())

sig_table <- function(rowData,data, ...){

  tablelist <- list()
  
  cols <- list(...)
  
  # loop version 2
  for (i in 1:length(cols)) {

    xtabs <- xtabs(~data[[rowData]]+data[[cols[[i]]]],data=data)
    
    chisq <- chisq.test(xtabs)
  
    std_res <- chisq$stdres

    xtabs <- prop.table(xtabs, margin = 2)
    
    xtabs <- apply(xtabs, 2, round, digits = 2)
  
    mytable <- format(xtabs, justify = "right")
    mytable[std_res > 2] <- paste(mytable[std_res > 2], intToUtf8(8593)) 
    mytable[std_res < -2] <- paste(mytable[std_res < -2], intToUtf8(8595))
  
    mytable <- as.data.frame(mytable)
    
    tablelist[[i]] <- mytable
    names(tablelist)[i] <- cols[i]
    
  }
  
  table <- do.call(cbind, tablelist)
  
  oldcolnames <- colnames(table)
  newcolnames <- lapply(oldcolnames, function(x) sub("^[^.]*\\.", "", x))
  for (i in 1:length(newcolnames)) {
    names(newcolnames)[i] <- oldcolnames[i]
  }
  
  table$rowname <- row.names(table) 
  
  gt <- table %>%
    gt(rowname_col = "rowname")

  gt <- gt %>%  tab_stubhead(label = rowData)

  for (i in 1:length(cols)) {
    gt <- gt %>%
      tab_spanner(label = cols[[i]], columns = starts_with(cols[[i]]))
  }

  gt <- gt %>%
    tab_style_body(
      style = cell_text(weight = "bold"),
      pattern = "↑"
    ) %>%
    tab_style_body(
      style = cell_text(weight = "bold"),
      pattern = "↓"
    )

  gt <- gt %>% cols_label(.list = newcolnames) %>%
    cols_align(columns = everything(),
             align = "left")

  return(gt)
}  

```


```{r echo=FALSE}

gt <- sig_table("gear", mtcars, "cyl", "vs", "am", "carb")

gt %>%
  tab_header(
    title = md("Significance Table"),
    subtitle = md("`This is a test")
  ) %>%
  as_latex()

```